# Generated by Django 2.0.6 on 2018-06-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl', models.IntegerField(default=None)),
                ('cl', models.IntegerField(default=None)),
                ('half_day', models.IntegerField(default=None)),
                ('comp_off', models.IntegerField(default=None)),
            ],
        ),
    ]
