# Generated by Django 2.0.6 on 2018-06-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leave',
            name='cl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='comp_off',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='half_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='pl',
            field=models.IntegerField(null=True),
        ),
    ]
